### ISSUE TITLE
The README is incorrect

### ISSUE THREAD

**Issue by groksrc** [dantswain/beanie#2]
The README documentation is slightly incorrect. There are a few typos and the step to authenticate to the docker API is left out.

**Comment by groksrc** [comment]
Needs Hacktoberfest label to apply

**Comment by jatinrajani** [comment]
Hi @groksrc 
I would love to contribute and fix typos.Can i contribute

**Comment by salman-bhai** [comment]
Hey is this Issue still open to contributions @groksrc
